//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic; // Required for ListBox

namespace GUI_DB
{
    partial class BookingDetailsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        // Controls for displaying booking details
        private System.Windows.Forms.Label lblHeader;
        private System.Windows.Forms.Label lblMovie;
        private System.Windows.Forms.Label lblShowtime;
        private System.Windows.Forms.Label lblTicketId;
        private System.Windows.Forms.Label lblUnitPrice;
        private System.Windows.Forms.Label lblTotalPrice;
        private System.Windows.Forms.Label lblBookingTime; // Added label for booking time
        private System.Windows.Forms.ListBox lstSeats;
        private System.Windows.Forms.Button btnBack;       // Only Back button needed
        private System.Windows.Forms.Panel contentPanel;   // Panel to hold controls
        private System.Windows.Forms.Label lblSeatsHeader; // Label for the seats list
        private System.Windows.Forms.Label lblReservationDate; // Added label for reservation date

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lblHeader = new System.Windows.Forms.Label();
            this.contentPanel = new System.Windows.Forms.Panel();
            this.lblMovie = new System.Windows.Forms.Label();
            this.lblShowtime = new System.Windows.Forms.Label();
            this.lblTicketId = new System.Windows.Forms.Label();
            this.lblBookingTime = new System.Windows.Forms.Label();
            this.lblSeatsHeader = new System.Windows.Forms.Label();
            this.lstSeats = new System.Windows.Forms.ListBox();
            this.lblUnitPrice = new System.Windows.Forms.Label();
            this.lblTotalPrice = new System.Windows.Forms.Label();
            this.btnBack = new System.Windows.Forms.Button();
            this.lblReservationDate = new System.Windows.Forms.Label();
            this.contentPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblHeader
            // 
            this.lblHeader.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblHeader.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblHeader.ForeColor = System.Drawing.Color.White;
            this.lblHeader.Location = new System.Drawing.Point(20, 19);
            this.lblHeader.Name = "lblHeader";
            this.lblHeader.Size = new System.Drawing.Size(632, 50);
            this.lblHeader.TabIndex = 0;
            this.lblHeader.Text = "Booking Details";
            this.lblHeader.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // contentPanel
            // 
            this.contentPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.contentPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.contentPanel.Controls.Add(this.lblReservationDate);
            this.contentPanel.Controls.Add(this.lblHeader);
            this.contentPanel.Controls.Add(this.lblMovie);
            this.contentPanel.Controls.Add(this.lblShowtime);
            this.contentPanel.Controls.Add(this.lblTicketId);
            this.contentPanel.Controls.Add(this.lblBookingTime);
            this.contentPanel.Controls.Add(this.lblSeatsHeader);
            this.contentPanel.Controls.Add(this.lstSeats);
            this.contentPanel.Controls.Add(this.lblUnitPrice);
            this.contentPanel.Controls.Add(this.lblTotalPrice);
            this.contentPanel.Controls.Add(this.btnBack);
            this.contentPanel.Location = new System.Drawing.Point(224, 31);
            this.contentPanel.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.contentPanel.Name = "contentPanel";
            this.contentPanel.Padding = new System.Windows.Forms.Padding(17, 19, 17, 19);
            this.contentPanel.Size = new System.Drawing.Size(675, 687);
            this.contentPanel.TabIndex = 0;
            // 
            // lblMovie
            // 
            this.lblMovie.AutoSize = true;
            this.lblMovie.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblMovie.ForeColor = System.Drawing.Color.White;
            this.lblMovie.Location = new System.Drawing.Point(20, 69);
            this.lblMovie.Name = "lblMovie";
            this.lblMovie.Size = new System.Drawing.Size(125, 28);
            this.lblMovie.TabIndex = 1;
            this.lblMovie.Text = "Movie: [Title]";
            // 
            // lblShowtime
            // 
            this.lblShowtime.AutoSize = true;
            this.lblShowtime.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblShowtime.ForeColor = System.Drawing.Color.White;
            this.lblShowtime.Location = new System.Drawing.Point(20, 108);
            this.lblShowtime.Name = "lblShowtime";
            this.lblShowtime.Size = new System.Drawing.Size(162, 28);
            this.lblShowtime.TabIndex = 2;
            this.lblShowtime.Text = "Showtime: [Time]";
            // 
            // lblTicketId
            // 
            this.lblTicketId.AutoSize = true;
            this.lblTicketId.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblTicketId.ForeColor = System.Drawing.Color.White;
            this.lblTicketId.Location = new System.Drawing.Point(22, 145);
            this.lblTicketId.Name = "lblTicketId";
            this.lblTicketId.Size = new System.Drawing.Size(127, 28);
            this.lblTicketId.TabIndex = 3;
            this.lblTicketId.Text = "Ticket ID: [ID]";
            // 
            // lblBookingTime
            // 
            this.lblBookingTime.AutoSize = true;
            this.lblBookingTime.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblBookingTime.ForeColor = System.Drawing.Color.LightGray;
            this.lblBookingTime.Location = new System.Drawing.Point(20, 186);
            this.lblBookingTime.Name = "lblBookingTime";
            this.lblBookingTime.Size = new System.Drawing.Size(196, 25);
            this.lblBookingTime.TabIndex = 9;
            this.lblBookingTime.Text = "Booked On: [DateTime]";
            // 
            // lblSeatsHeader
            // 
            this.lblSeatsHeader.AutoSize = true;
            this.lblSeatsHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblSeatsHeader.ForeColor = System.Drawing.Color.White;
            this.lblSeatsHeader.Location = new System.Drawing.Point(20, 262);
            this.lblSeatsHeader.Name = "lblSeatsHeader";
            this.lblSeatsHeader.Size = new System.Drawing.Size(153, 28);
            this.lblSeatsHeader.TabIndex = 10;
            this.lblSeatsHeader.Text = "Selected Seats:";
            // 
            // lstSeats
            // 
            this.lstSeats.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstSeats.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(55)))), ((int)(((byte)(70)))));
            this.lstSeats.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lstSeats.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lstSeats.ForeColor = System.Drawing.Color.White;
            this.lstSeats.FormattingEnabled = true;
            this.lstSeats.ItemHeight = 28;
            this.lstSeats.Location = new System.Drawing.Point(24, 300);
            this.lstSeats.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.lstSeats.Name = "lstSeats";
            this.lstSeats.SelectionMode = System.Windows.Forms.SelectionMode.None;
            this.lstSeats.Size = new System.Drawing.Size(628, 114);
            this.lstSeats.TabIndex = 4;
            // 
            // lblUnitPrice
            // 
            this.lblUnitPrice.AutoSize = true;
            this.lblUnitPrice.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblUnitPrice.ForeColor = System.Drawing.Color.White;
            this.lblUnitPrice.Location = new System.Drawing.Point(20, 450);
            this.lblUnitPrice.Name = "lblUnitPrice";
            this.lblUnitPrice.Size = new System.Drawing.Size(192, 28);
            this.lblUnitPrice.TabIndex = 5;
            this.lblUnitPrice.Text = "Price Per Seat: [Price]";
            // 
            // lblTotalPrice
            // 
            this.lblTotalPrice.AutoSize = true;
            this.lblTotalPrice.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.lblTotalPrice.ForeColor = System.Drawing.Color.White;
            this.lblTotalPrice.Location = new System.Drawing.Point(20, 488);
            this.lblTotalPrice.Name = "lblTotalPrice";
            this.lblTotalPrice.Size = new System.Drawing.Size(143, 30);
            this.lblTotalPrice.TabIndex = 6;
            this.lblTotalPrice.Text = "Total: [Total]";
            // 
            // btnBack
            // 
            this.btnBack.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnBack.BackColor = System.Drawing.Color.Gray;
            this.btnBack.FlatAppearance.BorderSize = 0;
            this.btnBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBack.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnBack.ForeColor = System.Drawing.Color.White;
            this.btnBack.Location = new System.Drawing.Point(258, 598);
            this.btnBack.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnBack.Name = "btnBack";
            this.btnBack.Size = new System.Drawing.Size(158, 56);
            this.btnBack.TabIndex = 8;
            this.btnBack.Text = "Back";
            this.btnBack.UseVisualStyleBackColor = false;
            // 
            // lblReservationDate
            // 
            this.lblReservationDate.AutoSize = true;
            this.lblReservationDate.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lblReservationDate.ForeColor = System.Drawing.Color.White;
            this.lblReservationDate.Location = new System.Drawing.Point(22, 225);
            this.lblReservationDate.Name = "lblReservationDate";
            this.lblReservationDate.Size = new System.Drawing.Size(168, 28);
            this.lblReservationDate.TabIndex = 5;
            this.lblReservationDate.Text = "Reservation Date: ";
            // 
            // BookingDetailsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(40)))));
            this.ClientSize = new System.Drawing.Size(1125, 750);
            this.Controls.Add(this.contentPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "BookingDetailsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Booking Details";
            this.Load += new System.EventHandler(this.BookingDetailsForm_Load);
            this.contentPanel.ResumeLayout(false);
            this.contentPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
    }
}