//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;
using System.Windows.Forms;

namespace GUI_DB
{
    partial class CustomerMovieListForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        // Declare the controls
        private System.Windows.Forms.Panel filterLayout; // Holds filters, back button, AND reservations
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanelMovies;
        private System.Windows.Forms.Button btnBack;
        private System.Windows.Forms.ComboBox cmbGenre;

        // *** NEW: Controls for Reservations Panel ***
        private System.Windows.Forms.Panel panelReservations;
        private System.Windows.Forms.Label lblReservationsHeader;
        private System.Windows.Forms.ListBox lstReservations;
        private System.Windows.Forms.Panel panelFilterControlsContainer; // *** NEW: Container for actual filters ***


        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.filterLayout = new System.Windows.Forms.Panel();
            this.panelFilterControlsContainer = new System.Windows.Forms.Panel(); // Initialize container
            this.btnBack = new System.Windows.Forms.Button();
            this.cmbGenre = new System.Windows.Forms.ComboBox();
            this.panelReservations = new System.Windows.Forms.Panel(); // Initialize reservations panel
            this.lblReservationsHeader = new System.Windows.Forms.Label(); // Initialize header label
            this.lstReservations = new System.Windows.Forms.ListBox(); // Initialize list box
            this.flowLayoutPanelMovies = new System.Windows.Forms.FlowLayoutPanel();
            this.filterLayout.SuspendLayout(); // Suspend layout for filterLayout
            this.panelFilterControlsContainer.SuspendLayout(); // Suspend layout for filter container
            this.panelReservations.SuspendLayout(); // Suspend layout for reservations panel
            this.SuspendLayout(); // Suspend layout for form

            //
            // filterLayout (Main Left Panel)
            //
            this.filterLayout.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(35)))), ((int)(((byte)(50)))));
            this.filterLayout.Controls.Add(this.panelReservations); // Add reservations panel first (will be docked bottom)
            this.filterLayout.Controls.Add(this.panelFilterControlsContainer); // Add filter container (will be docked top/fill)
            this.filterLayout.Dock = System.Windows.Forms.DockStyle.Left;
            this.filterLayout.Location = new System.Drawing.Point(0, 0);
            this.filterLayout.Name = "filterLayout";
            // Padding removed here, will be applied to inner panels
            this.filterLayout.Size = new System.Drawing.Size(220, 600); // Adjust width as needed
            this.filterLayout.TabIndex = 0;

            //
            // panelFilterControlsContainer (Holds Back Button and Dynamic Filters)
            //
            this.panelFilterControlsContainer.Controls.Add(this.btnBack);
            // Note: Filter controls (Age Radio, Genre Combo) will be added dynamically via AddFilterControl to THIS panel
            this.panelFilterControlsContainer.Dock = System.Windows.Forms.DockStyle.Fill; // Takes space above reservations
            this.panelFilterControlsContainer.Location = new System.Drawing.Point(0, 0);
            this.panelFilterControlsContainer.Name = "panelFilterControlsContainer";
            this.panelFilterControlsContainer.Padding = new System.Windows.Forms.Padding(10); // Add padding here
            this.panelFilterControlsContainer.Size = new System.Drawing.Size(220, 350); // Example Size, adjust relative to reservations
            this.panelFilterControlsContainer.TabIndex = 1; // Tab index after filterLayout

            //
            // btnBack (Now inside panelFilterControlsContainer)
            //
            this.btnBack.BackColor = System.Drawing.Color.Gray;
            this.btnBack.Dock = System.Windows.Forms.DockStyle.Top; // Dock to top of its container
            this.btnBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBack.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBack.ForeColor = System.Drawing.Color.White;
            this.btnBack.Location = new System.Drawing.Point(10, 10); // Position respecting container padding
            this.btnBack.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10); // Add margin below button
            this.btnBack.Name = "btnBack";
            this.btnBack.Size = new System.Drawing.Size(200, 40); // Use container width minus padding
            this.btnBack.TabIndex = 0; // First control in this container
            this.btnBack.Text = "Back";
            this.btnBack.UseVisualStyleBackColor = false;
            // Click event handler attached in .cs file

            //
            // cmbGenre (Instance used by AddFilterControl, not directly added here)
            //
            this.cmbGenre.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(75)))));
            this.cmbGenre.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGenre.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbGenre.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbGenre.ForeColor = System.Drawing.Color.White;
            this.cmbGenre.FormattingEnabled = true;
            this.cmbGenre.Name = "cmbGenre";
            // Size and location are set dynamically in AddFilterControl

            //
            // panelReservations (NEW - Bottom Left Panel)
            //
            this.panelReservations.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(55))))); // Slightly different background
            this.panelReservations.Controls.Add(this.lstReservations);
            this.panelReservations.Controls.Add(this.lblReservationsHeader);
            this.panelReservations.Dock = System.Windows.Forms.DockStyle.Bottom; // Dock to bottom of filterLayout
            this.panelReservations.Location = new System.Drawing.Point(0, 350); // Position below filter container
            this.panelReservations.Name = "panelReservations";
            this.panelReservations.Padding = new System.Windows.Forms.Padding(10, 5, 10, 10); // Padding inside this panel
            this.panelReservations.Size = new System.Drawing.Size(220, 250); // Adjust height as needed
            this.panelReservations.TabIndex = 2; // Tab index after filter container

            //
            // lblReservationsHeader (NEW - Inside panelReservations)
            //
            this.lblReservationsHeader.BackColor = System.Drawing.Color.Transparent; // Match panel background
            this.lblReservationsHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblReservationsHeader.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblReservationsHeader.ForeColor = System.Drawing.Color.White;
            this.lblReservationsHeader.Location = new System.Drawing.Point(10, 5); // Use padding for position
            this.lblReservationsHeader.Name = "lblReservationsHeader";
            this.lblReservationsHeader.Size = new System.Drawing.Size(200, 30); // Span width with padding, set height
            this.lblReservationsHeader.TabIndex = 0;
            this.lblReservationsHeader.Text = "My Reservations";
            this.lblReservationsHeader.TextAlign = System.Drawing.ContentAlignment.MiddleLeft; // Align text

            //
            // lstReservations (NEW - Inside panelReservations)
            //
            this.lstReservations.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(65))))); // List background
            this.lstReservations.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lstReservations.Dock = System.Windows.Forms.DockStyle.Fill; // Fill remaining space in panelReservations
            this.lstReservations.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed; // Required for custom color/drawing
            this.lstReservations.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lstReservations.ForeColor = System.Drawing.Color.White; // Default Text color
            this.lstReservations.FormattingEnabled = true;
            this.lstReservations.IntegralHeight = false; // Allows partial items if needed
            this.lstReservations.ItemHeight = 20; // Adjust item height for readability
            this.lstReservations.Location = new System.Drawing.Point(10, 35); // Position below header (respecting header height and panel padding)
            this.lstReservations.Name = "lstReservations";
            this.lstReservations.Size = new System.Drawing.Size(200, 205); // Fill available space (height = panel height - padding - header height)
            this.lstReservations.TabIndex = 1;
            // Event handlers (DrawItem, SelectedIndexChanged) attached in .cs file

            //
            // flowLayoutPanelMovies (Main Right Panel)
            //
            this.flowLayoutPanelMovies.AutoScroll = true;
            this.flowLayoutPanelMovies.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(60)))));
            this.flowLayoutPanelMovies.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanelMovies.Location = new System.Drawing.Point(this.filterLayout.Width, 0); // Position next to filterLayout
            this.flowLayoutPanelMovies.Name = "flowLayoutPanelMovies";
            this.flowLayoutPanelMovies.Padding = new System.Windows.Forms.Padding(10);
            this.flowLayoutPanelMovies.Size = new System.Drawing.Size(780, 600); // Adjust width if filterLayout changes (form width - filter layout width)
            this.flowLayoutPanelMovies.TabIndex = 3; // Tab index after left panel


            //
            // CustomerMovieListForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1000, 600); // Keep form size consistent
            this.Controls.Add(this.flowLayoutPanelMovies); // Add movie panel first (painted underneath left panel)
            this.Controls.Add(this.filterLayout); // Add left panel last (painted on top)
            this.Name = "CustomerMovieListForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Select Movie and Showtime";
            this.Load += new System.EventHandler(this.CustomerMovieListForm_Load_1); // Keep existing load event

            // Resume Layouts
            this.filterLayout.ResumeLayout(false);
            this.panelFilterControlsContainer.ResumeLayout(false);
            this.panelReservations.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

    }
}